### ISSUE TITLE
회원가입 및 로그인 기능을 한 액티비티에서 수행

### ISSUE THREAD

**Issue by 0x1306e6d** [openpnu/GoPNU#1]
이메일 주소로 로그인 시 한 액티비티에서 회원가입 및 로그인 기능을 수행하도록 수정 필요.

초기 화면에는 이메일 주소와 비밀번호 입력만 가능하며, 회원가입 버튼 클릭 시 비밀번호 체크 까지 보여줌.
뷰의 배치는 어떻게 할 것인지 논의가 필요해 보임. 아마 다음과 같을 듯.

```

- 이메일 주소 입력
- 비밀번호 입력
- 비밀번호 확인 입력 (숨겨짐)
- 공백?
- 회원가입 버튼
- 로그인 버튼

```

액티비티 이름을 `SignInActivity`, `SignInByEmailActivity`에서 `AuthenticationActivity` (미정)으로 변경하는 것이 좋아보임.

**Comment by Hyeonwoo-Park** [comment]
회원가입 및 로그인을 구글 파이어베이스로 통합하였습니다.
